import gymnasium
import argparse
import numpy as np
from einops import rearrange
import torch
from collections import deque
from tqdm import tqdm
import colorama
import os
import pandas as pd
from pathlib import Path
import math

from utils import seed_np_torch, WandbLogger
from replay_buffer import ReplayBuffer
import agents
from sub_models.world_models import WorldModel
from mamba_ssm import InferenceParams
from profiling import profile
import yaml
from envs.my_memory_maze import MemoryMaze
from envs.my_atari import Atari
from eval import eval_episodes
import warnings
import ast


# Action IDs produced by play.py key mapping and their expected ALE meanings.
PLAY_KEY_ACTION_MEANING = {
    0: "NOOP",
    1: "FIRE",
    2: "UP",
    3: "RIGHT",
    4: "LEFT",
    5: "DOWN",
    6: "UPRIGHT",
    7: "UPLEFT",
    8: "DOWNRIGHT",
    9: "DOWNLEFT",
    10: "UPFIRE",
    11: "RIGHTFIRE",
    12: "LEFTFIRE",
    13: "DOWNFIRE",
    14: "UPRIGHTFIRE",
    15: "UPLEFTFIRE",
    16: "DOWNRIGHTFIRE",
    17: "DOWNLEFTFIRE",
}


def _get_nested_config(config, key_path, default):
    current = config
    for key in key_path.split('.'):
        if isinstance(current, dict) and key in current:
            current = current[key]
        else:
            return default
    return current


def _normalise_token(text):
    return "".join(ch.lower() for ch in str(text) if ch.isalnum())


def _extract_action_meanings(env):
    if hasattr(env, '_env') and hasattr(env._env, 'unwrapped') and hasattr(env._env.unwrapped, 'get_action_meanings'):
        return list(env._env.unwrapped.get_action_meanings())
    if hasattr(env, 'unwrapped') and hasattr(env.unwrapped, 'get_action_meanings'):
        return list(env.unwrapped.get_action_meanings())
    return None


def _find_demo_files(demo_dir, env_name):
    demo_root = Path(demo_dir)
    if not demo_root.exists():
        return []

    all_files = sorted(demo_root.glob('*.npz'))
    if not all_files:
        return []

    if str(env_name).startswith('ALE/'):
        game_name = str(env_name).split('/')[-1].split('-')[0]
        game_token = _normalise_token(game_name)
        matched = [file_path for file_path in all_files if game_token in _normalise_token(file_path.stem)]
        # if matched:
        return matched

    return all_files


def _load_npz_demo(demo_path):
    with np.load(demo_path, allow_pickle=False) as data:
        required = {'obs', 'action', 'reward'}
        missing = required.difference(set(data.files))
        if missing:
            raise ValueError(f"{demo_path} is missing required keys: {sorted(missing)}")

        obs = data['obs']
        action = data['action']
        reward = data['reward']

        if 'termination' in data.files:
            termination = data['termination']
        elif 'done' in data.files:
            # play.py stores 'done', which is the episode-end flag.
            termination = data['done']
        else:
            raise ValueError(f"{demo_path} must include either 'termination' or 'done'.")

    return obs, action, reward, termination


def _validate_demo_actions(action_array, env, strict_action_check=True):
    if action_array.size == 0:
        return action_array.astype(np.int64), []

    if np.issubdtype(action_array.dtype, np.integer):
        action_array = action_array.astype(np.int64)
    else:
        if not np.all(np.isclose(action_array, np.round(action_array))):
            raise ValueError('Demonstration action contains non-integer values.')
        action_array = np.round(action_array).astype(np.int64)

    unique_actions = sorted(np.unique(action_array).tolist())

    action_n = env.action_space.n
    invalid_actions = [a for a in unique_actions if a < 0 or a >= action_n]
    if invalid_actions:
        raise ValueError(
            f'Demonstration action id out of range for current env action space (n={action_n}): {invalid_actions}'
        )

    if strict_action_check:
        unexpected_actions = [a for a in unique_actions if a not in PLAY_KEY_ACTION_MEANING]
        if unexpected_actions:
            raise ValueError(
                'Demonstration action ids are not generated by play.py mapping: '
                f'{unexpected_actions}'
            )

        action_meanings = _extract_action_meanings(env)
        if action_meanings is not None:
            mismatches = []
            for action_id in unique_actions:
                if action_id >= len(action_meanings):
                    mismatches.append((action_id, PLAY_KEY_ACTION_MEANING[action_id], 'OUT_OF_RANGE'))
                    continue

                expected = PLAY_KEY_ACTION_MEANING[action_id]
                actual = action_meanings[action_id]
                if expected != actual:
                    mismatches.append((action_id, expected, actual))

            if mismatches:
                mismatch_msg = ', '.join(
                    [f'id={aid}: expected={exp}, actual={act}' for aid, exp, act in mismatches]
                )
                raise ValueError(
                    'Action meaning mismatch between play.py key mapping and training environment: '
                    f'{mismatch_msg}'
                )

    return action_array, unique_actions


class TrainEnvAdapter(gymnasium.Env):
    """Adapter to make custom envs compatible with gymnasium vector envs."""
    metadata = {}

    def __init__(self, env, obs_shape, terminal_from_done=False):
        self._env = env
        self.observation_space = gymnasium.spaces.Box(0, 255, shape=obs_shape, dtype=np.uint8)
        self.action_space = env.action_space
        self._terminal_from_done = terminal_from_done

    def reset(self, *, seed=None, options=None):
        obs, info = self._env.reset()
        if "is_first" not in info:
            info["is_first"] = True
        return obs, info

    def step(self, action):
        obs, reward, done, info = self._env.step(action)
        if self._terminal_from_done:
            terminated = bool(done)
        else:
            terminated = bool(info.get("is_terminal", False))
            if "is_terminal" not in info:
                terminated = bool(done)
        truncated = bool(done) and not terminated
        info["is_terminal"] = terminated
        return obs, reward, terminated, truncated, info

    def close(self):
        return self._env.close()


def build_vector_env(config):
    num_envs = int(config.JointTrainAgent.NumEnvs)
    obs_shape = (
        config.BasicSettings.ImageSize,
        config.BasicSettings.ImageSize,
        config.BasicSettings.ImageChannel,
    )
    env_name = config.BasicSettings.Env_name
    base_seed = int(config.BasicSettings.Seed)

    def make_env(rank):
        def _init():
            if env_name.startswith('ALE'):
                base_env = Atari(
                    env_name,
                    size=(config.BasicSettings.ImageSize, config.BasicSettings.ImageSize),
                    seed=base_seed + rank,
                )
                terminal_from_done = False
            elif env_name.startswith('memory'):
                base_env = MemoryMaze(
                    env_name,
                    size=(config.BasicSettings.ImageSize, config.BasicSettings.ImageSize),
                    seed=base_seed + rank,
                )
                terminal_from_done = True
            else:
                raise ValueError(f'Unknown environment name: {env_name}')
            return TrainEnvAdapter(base_env, obs_shape, terminal_from_done=terminal_from_done)
        return _init

    env_fns = [make_env(rank) for rank in range(num_envs)]
    return gymnasium.vector.AsyncVectorEnv(env_fns=env_fns)


def preload_play_demonstrations(config, replay_buffer: ReplayBuffer, env):
    default_enable = Path('demonstrations').exists()
    use_demo = bool(_get_nested_config(config, 'Demonstration.Enable', default_enable))
    if not use_demo:
        print('Demonstration preload disabled. Skipping demo insertion.')
        return 0

    demo_dir = _get_nested_config(config, 'Demonstration.Directory', 'demonstrations')
    max_files = int(_get_nested_config(config, 'Demonstration.MaxFiles', 0))
    strict_action_check = bool(_get_nested_config(config, 'Demonstration.StrictActionCheck', True))

    demo_files = _find_demo_files(demo_dir, config.BasicSettings.Env_name)
    if max_files > 0:
        demo_files = demo_files[:max_files]

    if not demo_files:
        print(f'No demonstration files found in {demo_dir}. Training continues without preload.')
        return 0

    expected_obs_shape = tuple(replay_buffer.obs_buffer.shape[1:])
    total_steps = 0
    used_action_ids = set()

    for demo_path in demo_files:
        if len(replay_buffer) >= replay_buffer.max_length:
            print('Replay buffer is full while loading demonstrations. Stopping preload early.')
            break

        obs, action, reward, termination = _load_npz_demo(demo_path)

        if obs.ndim != 4 or tuple(obs.shape[1:]) != expected_obs_shape:
            raise ValueError(
                f'{demo_path} observation shape mismatch. '
                f'Expected (T, {expected_obs_shape[0]}, {expected_obs_shape[1]}, {expected_obs_shape[2]}), got {obs.shape}'
            )

        if not (len(obs) == len(action) == len(reward) == len(termination)):
            raise ValueError(
                f'{demo_path} has inconsistent lengths: '
                f'obs={len(obs)}, action={len(action)}, reward={len(reward)}, termination={len(termination)}'
            )

        if len(obs) == 0:
            print(f'Skipping empty demonstration file: {demo_path}')
            continue

        if obs.dtype != np.uint8:
            obs = obs.astype(np.uint8)

        action, unique_actions = _validate_demo_actions(action, env, strict_action_check=strict_action_check)
        used_action_ids.update(unique_actions)

        reward = reward.astype(np.float32)
        termination = (termination.astype(np.float32) > 0.5).astype(np.float32)

        # The first transition is episode start; every step after a terminal is also a new episode start.
        is_first = np.zeros_like(termination, dtype=np.float32)
        is_first[0] = 1.0
        if len(is_first) > 1:
            is_first[1:] = termination[:-1]

        steps_to_insert = min(len(obs), replay_buffer.max_length - len(replay_buffer))
        if steps_to_insert < len(obs):
            print(
                f'Truncating {demo_path} from {len(obs)} to {steps_to_insert} steps due to replay buffer capacity.'
            )

        for i in range(steps_to_insert):
            replay_buffer.append(obs[i], float(action[i]), float(reward[i]), float(termination[i]), float(is_first[i]))

        total_steps += steps_to_insert
        print(f'Loaded {steps_to_insert} transitions from {demo_path}.')

    if total_steps == 0:
        print('No demonstration transitions were loaded into replay buffer.')
        return 0

    action_meanings = _extract_action_meanings(env)
    if action_meanings is not None and used_action_ids:
        summary = ', '.join([f'{aid}:{action_meanings[aid]}' for aid in sorted(used_action_ids)])
        print(f'Validated demonstration action mapping (id:meaning): {summary}')

    print(
        colorama.Fore.CYAN
        + f'Preloaded {total_steps} demonstration transitions into replay buffer.'
        + colorama.Style.RESET_ALL
    )
    return total_steps


@profile
def train_world_model_step(replay_buffer: ReplayBuffer, world_model: WorldModel, batch_size, batch_length, logger, epoch, global_step, micro_batch_size=None):
    epoch_reconstruction_loss_list = []
    epoch_reward_loss_list = []
    epoch_termination_loss_list = []
    epoch_dynamics_loss_list = []
    epoch_dynamics_real_kl_div_list = []
    epoch_representation_loss_list = []
    epoch_representation_real_kl_div_list = []
    epoch_total_loss_list = []
    epoch_contrastive_loss_list = []
    epoch_contrastive_acc_list = []
    epoch_important_hash_loss_list = []
    if micro_batch_size is None or micro_batch_size <= 0:
        micro_batch_size = batch_size
    micro_batch_size = min(int(micro_batch_size), int(batch_size))
    accum_steps = max(1, int(math.ceil(batch_size / micro_batch_size)))

    reward_mean, reward_std = replay_buffer.get_reward_stats()

    for e in range(epoch):
        for micro_step in range(accum_steps):
            obs, action, reward, termination, is_first = replay_buffer.sample(
                micro_batch_size, batch_length, imagine=False
            )
            do_step = micro_step == accum_steps - 1
            outputs = world_model.update(
                obs,
                action,
                reward,
                termination,
                is_first,
                global_step=global_step,
                epoch_step=e,
                logger=logger if do_step else None,
                grad_accum_steps=accum_steps,
                do_step=do_step,
                zero_grad=micro_step == 0,
                reward_mean=reward_mean,
                reward_std=reward_std
            )

            if len(outputs) == 11:
                reconstruction_loss, reward_loss, termination_loss, \
                dynamics_loss, dynamics_real_kl_div, representation_loss, \
                representation_real_kl_div, total_loss, contrastive_loss, contrastive_acc, \
                important_hash_loss = outputs
            elif len(outputs) == 10:
                reconstruction_loss, reward_loss, termination_loss, \
                dynamics_loss, dynamics_real_kl_div, representation_loss, \
                representation_real_kl_div, total_loss, contrastive_loss, contrastive_acc = outputs
                important_hash_loss = 0.0
            else:
                reconstruction_loss, reward_loss, termination_loss, \
                dynamics_loss, dynamics_real_kl_div, representation_loss, \
                representation_real_kl_div, total_loss = outputs
                contrastive_loss, contrastive_acc = 0.0, 0.0
                important_hash_loss = 0.0

            epoch_reconstruction_loss_list.append(reconstruction_loss)
            epoch_reward_loss_list.append(reward_loss)
            epoch_termination_loss_list.append(termination_loss)
            epoch_dynamics_loss_list.append(dynamics_loss)
            epoch_dynamics_real_kl_div_list.append(dynamics_real_kl_div)
            epoch_representation_loss_list.append(representation_loss)
            epoch_representation_real_kl_div_list.append(representation_real_kl_div)
            epoch_total_loss_list.append(total_loss)
            epoch_contrastive_loss_list.append(contrastive_loss)
            epoch_contrastive_acc_list.append(contrastive_acc)
            epoch_important_hash_loss_list.append(important_hash_loss)
    if logger is not None:
        logger.log("WorldModel/reconstruction_loss", np.mean(epoch_reconstruction_loss_list), global_step=global_step)
        # logger.log("WorldModel/augmented_reconstruction_loss", augmented_reconstruction_loss.item(), global_step=global_step)
        logger.log("WorldModel/reward_loss",np.mean(epoch_reward_loss_list), global_step=global_step)
        logger.log("WorldModel/termination_loss", np.mean(epoch_termination_loss_list), global_step=global_step)
        logger.log("WorldModel/dynamics_loss", np.mean(epoch_dynamics_loss_list), global_step=global_step)
        logger.log("WorldModel/dynamics_real_kl_div", np.mean(epoch_dynamics_real_kl_div_list), global_step=global_step)
        logger.log("WorldModel/representation_loss", np.mean(epoch_representation_loss_list), global_step=global_step)
        logger.log("WorldModel/representation_real_kl_div", np.mean(epoch_representation_real_kl_div_list), global_step=global_step)
        logger.log("WorldModel/contrastive_loss", np.mean(epoch_contrastive_loss_list), global_step=global_step)
        logger.log("WorldModel/contrastive_acc", np.mean(epoch_contrastive_acc_list), global_step=global_step)
        logger.log("WorldModel/important_info_hash_loss", np.mean(epoch_important_hash_loss_list), global_step=global_step)
        logger.log("WorldModel/total_loss", np.mean(epoch_total_loss_list), global_step=global_step)

@profile
@torch.no_grad()
def world_model_imagine_data(replay_buffer: ReplayBuffer,
                             world_model: WorldModel, agent: agents.ActorCriticAgent,
                             imagine_batch_size,
                             imagine_context_length, imagine_batch_length,
                             log_video, logger, global_step):
    '''
    Sample context from replay buffer, then imagine data with world model and agent
    '''
    world_model.eval()
    agent.eval()
    sample_obs, sample_action, sample_reward, sample_termination, sample_is_first = replay_buffer.sample(
        imagine_batch_size, imagine_context_length, imagine=True)
    if world_model.model == 'Transformer':
        latent, action, old_logits, context_latent, reward_hat, termination_hat = world_model.imagine_data(
            agent, sample_obs, sample_action, sample_is_first,
            imagine_batch_size=imagine_batch_size,
            imagine_batch_length=imagine_batch_length,
            log_video=log_video,
            logger=logger, global_step=global_step
        )
    elif world_model.model in ['Mamba', 'Mamba2', 'Mamba3']:
         latent, action, old_logits, context_latent, reward_hat, termination_hat = world_model.imagine_data2(
            agent, sample_obs, sample_action, sample_reward, sample_is_first,
            imagine_batch_size=imagine_batch_size,
            imagine_batch_length=imagine_batch_length,
            log_video=log_video,
            logger=logger, global_step=global_step
        )
    return latent, action, old_logits, context_latent, sample_reward, sample_termination, reward_hat, termination_hat

@profile
def joint_train_world_model_agent(config, logdir,
                                  replay_buffer: ReplayBuffer,
                                  world_model: WorldModel, agent: agents.ActorCriticAgent,
                                  logger,
                                  demo_steps=0):
    os.makedirs(f"{logdir}/ckpt", exist_ok=True)

    vec_env = build_vector_env(config)
    num_envs = int(config.JointTrainAgent.NumEnvs)
    print("Current env: " + colorama.Fore.YELLOW + f"{config.BasicSettings.Env_name}" + colorama.Style.RESET_ALL)

    atari_benchmark_df = pd.read_csv("atari_performance.csv", index_col='Task', usecols=lambda column: column in ['Task', 'Alien', 'Amidar', 'Assault', 'Asterix', 'BankHeist', 'BattleZone', 'Boxing', 'Breakout', 'ChopperCommand', 'CrazyClimber', 'DemonAttack', 'Freeway', 'Frostbite', 'Gopher', 'Hero', 'Jamesbond', 'Kangaroo', 'Krull', 'KungFuMaster', 'MsPacman', 'Pong', 'PrivateEye', 'Qbert', 'RoadRunner', 'Seaquest', 'UpNDown'])
    atari_pure_name = config.BasicSettings.Env_name.split('/')[-1].split('-')[0]
    game_benchmark_df = atari_benchmark_df.get(atari_pure_name)
    
    sum_reward = np.zeros(num_envs, dtype=np.float32)
    current_ob, _ = vec_env.reset()
    current_is_first = np.ones(num_envs, dtype=np.float32)
    context_obs = deque(maxlen=config.JointTrainAgent.RealityContextLength)
    context_action = deque(maxlen=config.JointTrainAgent.RealityContextLength)
    context_reward = deque(maxlen=config.JointTrainAgent.RealityContextLength)
    context_is_first = deque(maxlen=config.JointTrainAgent.RealityContextLength)

    # === [수정] 오프라인 사전 학습 (Offline Pre-training) 구간 ===
    if demo_steps > 0:
        # 데몬스트레이션 스텝 수를 학습 주기 단위로 환산하되, num_envs에 반비례하도록 나누어 사전 학습 비중을 보정
        pretrain_updates = (demo_steps // num_envs) // config.JointTrainAgent.TrainDynamicsEverySteps
        print(colorama.Fore.CYAN + f"\nStarting Offline Pre-training: {pretrain_updates} updates (scaled down by num_envs={num_envs}) using demonstration data..." + colorama.Style.RESET_ALL)
        
        for p_step in tqdm(range(pretrain_updates), desc='Pre-training (Offline)'):
            # 로깅용 가상 스텝 (온라인 수집 템포에 맞추어 num_envs 배율 적용)
            pseudo_global_step = p_step * config.JointTrainAgent.TrainDynamicsEverySteps * num_envs
            
            # 1. World Model 사전 학습
            if replay_buffer.ready('world_model'):
                wm_micro_batch_size = int(_get_nested_config(
                    config,
                    'JointTrainAgent.WorldModelMicroBatchSize',
                    config.JointTrainAgent.BatchSize,
                ))
                train_world_model_step(
                    replay_buffer=replay_buffer,
                    world_model=world_model,
                    batch_size=config.JointTrainAgent.BatchSize,
                    batch_length=config.JointTrainAgent.BatchLength,
                    logger=logger,
                    epoch=config.JointTrainAgent.TrainDynamicsEpoch,
                    global_step=pseudo_global_step,
                    micro_batch_size=wm_micro_batch_size,
                )

            # 2. Behaviour Model 사전 학습
            # Agent 업데이트 조건도 스케일링을 반영하여 기존과 동일한 비율로 업데이트되도록 유지
            if replay_buffer.ready('behaviour') and pseudo_global_step % (config.JointTrainAgent.TrainAgentEverySteps * num_envs) == 0:
                imagine_latent, agent_action, old_logits, context_latent, imagined_context_reward, imagined_context_termination, imagine_reward, imagine_termination = world_model_imagine_data(
                    replay_buffer=replay_buffer,
                    world_model=world_model,
                    agent=agent,
                    imagine_batch_size=config.JointTrainAgent.ImagineBatchSize,
                    imagine_context_length=config.JointTrainAgent.ImagineContextLength,
                    imagine_batch_length=config.JointTrainAgent.ImagineBatchLength,
                    log_video=False, # 훈련 속도를 위해 사전 학습 중 비디오 로깅은 생략
                    logger=logger,
                    global_step=pseudo_global_step
                )

                agent.update(
                    latent=imagine_latent,
                    action=agent_action,
                    old_logits=old_logits,
                    context_latent=context_latent,
                    context_reward=imagined_context_reward,
                    context_termination=imagined_context_termination,
                    reward=imagine_reward,
                    termination=imagine_termination,
                    logger=logger,
                    global_step=pseudo_global_step
                )
        print(colorama.Fore.GREEN + "Offline Pre-training Complete!\n" + colorama.Style.RESET_ALL)
    # =========================================================

    remaining_steps = max(0, config.JointTrainAgent.SampleMaxSteps - demo_steps)
    total_iters = config.JointTrainAgent.SampleMaxSteps // num_envs
    initial_iters = demo_steps // num_envs

    # sample and train (Online)
    for total_steps in tqdm(range(remaining_steps // num_envs), 
                            desc='Training (Online)',
                            initial=initial_iters,
                            total=total_iters):
        
        # [수정] 현재 스텝과 직전 스텝 계산 (경계 교차 기법용)
        global_step = demo_steps + total_steps * num_envs
        prev_global_step = global_step - num_envs 
        
        wm_ready = replay_buffer.ready('world_model')
        
        # sample part >>>
        if wm_ready:
            world_model.eval()
            agent.eval()
            with torch.no_grad():
                if len(context_action) == 0:
                    action = vec_env.action_space.sample()
                else:
                    context_latent = world_model.encode_obs(torch.cat(list(context_obs), dim=1).to(world_model.device))
                    model_context_action = np.stack(list(context_action), axis=1)
                    model_context_action = torch.as_tensor(model_context_action, device=world_model.device)

                    model_context_reward = np.stack(list(context_reward), axis=1)
                    model_context_reward = torch.as_tensor(model_context_reward, device=world_model.device)

                    model_context_is_first = np.stack(list(context_is_first), axis=1)
                    model_context_is_first = torch.as_tensor(model_context_is_first, device=world_model.device)

                    if world_model.model == 'Transformer':
                        prior_flattened_sample, last_dist_feat = world_model.calc_last_dist_feat(
                            context_latent,
                            model_context_action,
                            is_first=model_context_is_first,
                        )
                    elif world_model.model in ['Mamba', 'Mamba2', 'Mamba3']:
                        prior_flattened_sample, last_dist_feat = world_model.calc_last_dist_feat(
                            context_latent,
                            model_context_action,
                            r=model_context_reward,
                            is_first=model_context_is_first,
                        )
                    action = agent.sample_as_env_action(
                        torch.cat([prior_flattened_sample, last_dist_feat], dim=-1),
                        greedy=False
                    )

            action = np.asarray(action)
            if action.ndim == 0:
                action = action[None]

            context_obs.append(rearrange(torch.Tensor(current_ob).to(world_model.device), "B H W C -> B 1 C H W")/255)
            context_action.append(action.copy())
            context_is_first.append(current_is_first.copy())
        else:
            action = vec_env.action_space.sample()
            action = np.asarray(action)
            if action.ndim == 0:
                action = action[None]

        ob, reward, terminated, truncated, info = vec_env.step(action)
        done_flag = np.logical_or(terminated, truncated)
        termination = terminated.astype(np.float32)
        for env_idx in range(num_envs):
            replay_buffer.append(
                current_ob[env_idx],
                action[env_idx],
                reward[env_idx],
                termination[env_idx],
                current_is_first[env_idx],
            )

        if wm_ready:
            context_reward.append(reward.copy())

        sum_reward += reward
        current_ob = ob
        current_is_first = done_flag.astype(np.float32)

        if done_flag.any():
            episode_frame_numbers = info.get("episode_frame_number")
            if episode_frame_numbers is not None:
                episode_frame_numbers = np.asarray(episode_frame_numbers)
            done_indices = np.where(done_flag)[0]
            for env_idx in done_indices:
                logger.log("episode/score", float(sum_reward[env_idx]), global_step=global_step)
                if episode_frame_numbers is not None:
                    logger.log("episode/length", float(episode_frame_numbers[env_idx]), global_step=global_step)
                if config.BasicSettings.Env_name.startswith('ALE'):
                    normalised_score = (sum_reward[env_idx] - game_benchmark_df['Random']) / (game_benchmark_df['Human'] - game_benchmark_df['Random'])
                    logger.log("episode/normalised score", float(normalised_score), global_step=global_step)
                    for algorithm in game_benchmark_df.index[2:]:
                        denominator = game_benchmark_df[algorithm] - game_benchmark_df['Random']
                        if denominator != 0:
                            normalized_score = (sum_reward[env_idx] - game_benchmark_df['Random']) / denominator
                            logger.log(f"benchmark/normalised {algorithm} score", float(normalized_score), global_step=global_step)

                sum_reward[env_idx] = 0.0

        # [수정] World Model 업데이트 조건 (경계 교차 기법)
        wm_train_every = config.JointTrainAgent.TrainDynamicsEverySteps
        if replay_buffer.ready('world_model') and (prev_global_step // wm_train_every < global_step // wm_train_every) and global_step <= config.JointTrainAgent.FreezeWorldModelAfterSteps:
            wm_micro_batch_size = int(_get_nested_config(
                config,
                'JointTrainAgent.WorldModelMicroBatchSize',
                config.JointTrainAgent.BatchSize,
            ))
            train_world_model_step(
                replay_buffer=replay_buffer,
                world_model=world_model,
                batch_size=config.JointTrainAgent.BatchSize,
                batch_length=config.JointTrainAgent.BatchLength,
                logger=logger,
                epoch=config.JointTrainAgent.TrainDynamicsEpoch,
                global_step=global_step,
                micro_batch_size=wm_micro_batch_size,
            )

        # [수정] Agent 업데이트 조건 (경계 교차 기법)
        agent_train_every = config.JointTrainAgent.TrainAgentEverySteps
        if replay_buffer.ready('behaviour') and (prev_global_step // agent_train_every < global_step // agent_train_every) and global_step <= config.JointTrainAgent.FreezeBehaviourAfterSteps:
            log_video = (prev_global_step // config.JointTrainAgent.SaveEverySteps < global_step // config.JointTrainAgent.SaveEverySteps)

            imagine_latent, agent_action, old_logits, context_latent, imagined_context_reward, imagined_context_termination, imagine_reward, imagine_termination = world_model_imagine_data(
                replay_buffer=replay_buffer,
                world_model=world_model,
                agent=agent,
                imagine_batch_size=config.JointTrainAgent.ImagineBatchSize,
                imagine_context_length=config.JointTrainAgent.ImagineContextLength,
                imagine_batch_length=config.JointTrainAgent.ImagineBatchLength,
                log_video=log_video,
                logger=logger,
                global_step=global_step
            )

            agent.update(
                latent=imagine_latent,
                action=agent_action,
                old_logits=old_logits,
                context_latent=context_latent,
                context_reward=imagined_context_reward,
                context_termination=imagined_context_termination,
                reward=imagine_reward,
                termination=imagine_termination,
                logger=logger,
                global_step=global_step
            )

        if config.Evaluate.DuringTraining and (prev_global_step // config.Evaluate.EverySteps < global_step // config.Evaluate.EverySteps) and (global_step > config.JointTrainAgent.WorldModelWarmUp or global_step == 0):
            _ = eval_episodes(config, world_model, agent, logger, global_step)
            
        if config.JointTrainAgent.SaveModels and (prev_global_step // config.JointTrainAgent.SaveEverySteps < global_step // config.JointTrainAgent.SaveEverySteps) and global_step > config.JointTrainAgent.WorldModelWarmUp:
            print(colorama.Fore.GREEN + f"Saving model at total steps {global_step}" + colorama.Style.RESET_ALL)
            torch.save(world_model.state_dict(), f"{logdir}/ckpt/world_model.pth")
            torch.save(agent.state_dict(), f"{logdir}/ckpt/agent.pth")



def build_world_model(conf, action_dim, device):
    return WorldModel(
        action_dim = action_dim,
        config = conf, 
        device = device
    ).cuda(device)


def build_agent(conf, action_dim, device):
    if conf.Models.Agent.Policy == 'AC':
        return agents.ActorCriticAgent(
            conf = conf,
            action_dim=action_dim,
            device = device
        ).cuda(device)
    elif conf.Models.Agent.Policy == 'PPO':
        return agents.PPOAgent(
            conf=conf,
            action_dim=action_dim,
            device = device
        ).cuda(device)        


class DotDict(dict):
    """Dictionary with dot notation access."""
    def __init__(self, *args, **kwargs):
        super(DotDict, self).__init__(*args, **kwargs)
        for key, value in self.items():
            if isinstance(value, dict):
                self[key] = DotDict(value)

    def __getattr__(self, item):
        try:
            value = self[item]
        except KeyError:
            raise AttributeError(f"'DotDict' object has no attribute '{item}'")
        if isinstance(value, dict):
            value = DotDict(value)
        return value

    __setattr__ = dict.__setitem__
    __delattr__ = dict.__delitem__

    def update_or_create(self, key_path, value):
        keys = key_path.split('.')
        d = self
        for key in keys[:-1]:
            if key not in d or not isinstance(d[key], dict):
                d[key] = DotDict()
            d = d[key]
        d[keys[-1]] = value

# Function to parse and update config from arguments
def parse_args_and_update_config(config, prefix=''):
    parser = argparse.ArgumentParser()

    # Map string dtype to torch dtype
    def dtype_mapper(dtype_str):
        dtype_map = {
            'float32': torch.float32,
            'float16': torch.float16,
            'bfloat16': torch.bfloat16
        }
        return dtype_map[dtype_str]

    def add_arguments(config, prefix=''):
        for key, value in config.items():
            if isinstance(value, dict):
                add_arguments(value, prefix + key + '.')
            elif isinstance(value, bool):
                # Special handling for boolean arguments
                parser.add_argument(f'--{prefix}{key}', type=lambda x: x.lower() in ['true', '1', 'yes'], default=value)
            elif key == 'dtype':
                # Special handling for dtype arguments
                parser.add_argument(f'--{prefix}{key}', type=dtype_mapper, default=value)
            elif isinstance(value, (list, dict)):
                # Use a custom converter for list/dict-like arguments
                parser.add_argument(f'--{prefix}{key}', type=lambda x: ast.literal_eval(x), default=value)
            else:
                parser.add_argument(f'--{prefix}{key}', type=type(value), default=value)

    def update_dict(d, keys, value):
        for key in keys[:-1]:
            d = d.setdefault(key, {})
        d[keys[-1]] = value

    add_arguments(config, prefix)
    
    args = parser.parse_args()
    args_dict = vars(args)
    
    for arg_key, arg_value in args_dict.items():
        if arg_value is not None:
            keys = arg_key.split('.')
            update_dict(config, keys, arg_value)
    
    return config

def update_model_parameters(config, world_model, agent):
    config.update_or_create('Models.WorldModel.TotalParamNum', sum([p.numel() for p in world_model.parameters()]))
    print(f'World model total parameters: {sum([p.numel() for p in world_model.parameters()]):,}')
    
    config.update_or_create('Models.WorldModel.BackboneParamNum', sum([p.numel() for p in world_model.sequence_model.parameters()]))
    print(f'Dynamic model parameters: {sum([p.numel() for p in world_model.sequence_model.parameters()]):,}')
    
    config.update_or_create('Models.WorldModel.EncoderParamNum', sum([p.numel() for p in world_model.encoder.parameters()]))
    print(f'Encoder parameters: {sum([p.numel() for p in world_model.encoder.parameters()]):,}')
    
    config.update_or_create('Models.WorldModel.DecoderParamNum', sum([p.numel() for p in world_model.image_decoder.parameters()]))
    print(f'Decoder parameters: {sum([p.numel() for p in world_model.image_decoder.parameters()]):,}')
    
    config.update_or_create('Models.WorldModel.DiscretisationLayerParamNum', sum([p.numel() for p in world_model.dist_head.parameters()]))
    print(f'Discretisation layer parameters: {sum([p.numel() for p in world_model.dist_head.parameters()]):,}')
    
    config.update_or_create('Models.Agent.ActorParamNum', sum([p.numel() for p in agent.actor.parameters()]))
    print(f'Actor parameters: {sum([p.numel() for p in agent.actor.parameters()]):,}')
    
    config.update_or_create('Models.Agent.CriticParamNum', sum([p.numel() for p in agent.critic.parameters()]))
    print(f'Critic parameters: {sum([p.numel() for p in agent.critic.parameters()]):,}')

if __name__ == "__main__":
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    torch.backends.cudnn.benchmark = True
    warnings.filterwarnings("ignore")

    with open('config_files/configure.yaml', 'r') as file:
        config = yaml.safe_load(file)

    config = parse_args_and_update_config(config)   
    config = DotDict(config)

    device = torch.device(config.BasicSettings.Device)
    # set seed
    seed_np_torch(seed=config.BasicSettings.Seed)

    
    # getting action_dim with dummy env
    if config.BasicSettings.Env_name.startswith('ALE'):
        dummy_env = Atari(config.BasicSettings.Env_name)
    elif config.BasicSettings.Env_name.startswith('memory'):
        dummy_env = MemoryMaze(config.BasicSettings.Env_name)
    else:
        assert ValueError(f'Unknown environment name: {config.BasicSettings.Env_name}')

    action_dim = dummy_env.action_space.n

    # build world model and agent
    world_model = build_world_model(config, action_dim, device=device)
    agent = build_agent(config, action_dim, device=device)
    update_model_parameters(config, world_model, agent)
    if (config.BasicSettings.Compile and os.name != "nt"):  # compilation is not supported on windows
        world_model = torch.compile(world_model)
        agent = torch.compile(agent)
    if config.BasicSettings.SavePath != 'None':
        print('Loading models')
        world_model.load_state_dict(torch.load(f"{config.BasicSettings.SavePath}/world_model.pth"))
        agent.load_state_dict(torch.load(f"{config.BasicSettings.SavePath}/agent.pth"))
   
    logger = WandbLogger(config=config, project=config.Wandb.Init.Project, mode=config.Wandb.Init.Mode)
    
    # 기존: logdir = f"./saved_models/{config.n}/{config.BasicSettings.Env_name}/{logger.run.id}"
    logdir = f"/home/jovyan/gpu-4-nodes-volume2/minjun/graduate_research/saved_models/{config.n}/{config.BasicSettings.Env_name}/{logger.run.id}"

    # build replay buffer
    replay_buffer = ReplayBuffer(
        config,
        device=device
    )

    try:
        # [수정] 반환되는 데몬스트레이션 스텝 수를 저장합니다.
        demo_steps = preload_play_demonstrations(config, replay_buffer, dummy_env)
    finally:
        dummy_env.close()

    # [수정] 데몬스트레이션 스텝을 환경 개수(num_envs)의 배수로 보정합니다.
    # (global_step % TrainEverySteps == 0 연산이 어긋나서 학습이 멈추는 치명적인 버그 방지)
    num_envs = int(config.JointTrainAgent.NumEnvs)
    demo_steps = (demo_steps // num_envs) * num_envs

    # train (인자에 demo_steps 전달)
    joint_train_world_model_agent(config, logdir, replay_buffer, world_model, agent, logger, demo_steps=demo_steps)

    logger.close()

# CUDA_VISIBLE_DEVICES=2 python train.py --Wandb.Init.Mode disabled